# docker-compose file for local development and testing with container image.
version: '3.2'
services:
  devserver: &devserver
    build:
      context: .
      dockerfile: compose/Dockerfile
    expose:
      - "8080"
    ports:
      - "8000:8080"
    depends_on:
      - "iar-db"
      - "hydra"
      - "lookupproxy"
    # For devserver, mount the local directory inside the container as a volume
    # to allow local changes to be reflected without having to re-build the
    # container.
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
        read_only: true
    env_file:
      - compose/base.env
  tox:
    <<: *devserver
    entrypoint: ["tox"]
    command: []
    env_file:
      - compose/base.env
      - compose/tox.env
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
        read_only: true
      - type: volume
        source: tox-data
        target: /tmp/tox-data
  migrate:
    <<: *devserver
    command: ["migrate"]
  shell:
    <<: *devserver
    command: ["shell"]
  iar-db:
    image: postgres:9.6
    env_file:
      - compose/base.env

  # Lookup proxy service
  lookupproxy:
    build:
      context: ./compose/
      dockerfile: lookupproxy.Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - "lookupproxy-db"
      - "hydra"
    env_file:
      - compose/lookupproxy.env
  lookupproxy-db:
    image: postgres:9.6
    env_file:
      - compose/lookupproxy.env

  # Hydra OAuth2 infrastructure
  consent:
    image: uisautomation/experimental-mock-consent-app
    env_file:
      - compose/hydra-consent.env
    ports:
      - "8090:8090"
  hydra:
    image: oryd/hydra:v0.11.6-alpine
    entrypoint: ["/tmp/start-hydra.sh"]
    ports:
      - "4444:4444"
      - "4445:4445"
    env_file:
      - compose/hydra.env
    depends_on:
      - hydra-db
      - consent
    volumes:
      - "./compose/start-hydra.sh:/tmp/start-hydra.sh/:ro"
  hydra-db:
    image: postgres:9.6
    env_file:
      - compose/hydra.env

volumes:
  # A persistent volume for tox to store its stuff. This allows caching of
  # virtualenvs between runs.
  tox-data:
