# docker-compose for testing with container image.
version: '3.2'
services:
  tox:
    build:
      context: .
      dockerfile: compose/Dockerfile
    depends_on:
      - "iar-db"
    entrypoint: ["tox"]
    command: []
    env_file:
      - compose/base.env
      - compose/tox.env
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
        read_only: true
      - type: volume
        source: tox-data
        target: /tmp/tox-data
  iar-db:
    image: postgres
    env_file:
      - compose/base.env

volumes:
  # A persistent volume for tox to store its stuff. This allows caching of
  # virtualenvs between runs.
  tox-data:
